### ISSUE TITLE
Red-black tree implementation in `qtreetbl.c` occasionally breaks red-black tree invariant #4 

### ISSUE THREAD

**Issue by frazar** [darmar-lt/qcontainers#2]
While using the `qtreetbl_m` module in a Fortran project of mine, I found out that the underlying red-black tree implementation occasionally breaks the red-black tree invariant #4 in certain conditions.
The full list of rules of red-black trees can be found on [Wikipedia](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree#Properties).

In order to analyse the problem I edited "qtreetbl.c" in [my own fork](https://github.com/frazar/qcontainers) of the repo, and [added a couple of functions](https://github.com/frazar/qcontainers/commit/0271f4408b5c3d7de15c6ace86fadc0d46e63267) that check the tree integrity after every single node insertion/removal and panic on violations of rules #4 and #5. 
This allowed me to find a unit test that shows how Invariant #4 gets violated after just 14 insertion/removal operations.

The series of operations leading to the issue are the following:
1. Insert "0 0 0 0 0 0 0 0 0 0 0 0"
2. Insert "0 0 0 0 0 0 0 0 0 0 1 0"
3. Insert "0 0 0 0 0 0 0 0 0 1 1 0"
4. Insert "0 0 0 0 0 0 0 0 0 0 1 1"
5. Remove "0 0 0 0 0 0 0 0 0 0 1 1"
6. Insert "0 0 0 0 0 0 0 0 0 0 1 1"
7. Insert "0 0 1 0 0 0 0 0 0 0 1 1"
8. Insert "0 0 0 0 0 0 1 0 0 0 1 1"
9. Insert "0 0 0 0 0 0 0 0 0 1 1 1"
10. Remove "0 0 0 0 0 0 0 0 0 1 1 0"
11. Insert "0 0 0 0 0 0 0 0 0 1 1 0"
12. Insert "1 0 0 0 0 0 0 0 0 1 1 0"
13. Insert "0 0 0 0 0 0 0 0 1 1 1 0"
14. Remove "0 0 0 0 0 0 0 0 1 1 1 0"

After that, the tree presents an invalid structure, where one of the red nodes has a red child.

I [added](https://github.com/frazar/qcontainers/commit/8bf40cc1692d7b26958c15654219bc11316674e2) a unit test in the "tests/test_treetbl.f90" file in my fork that performs the operations described above, making the program panic.
The following steps should allow anyone to reproduce the test failure:
1. Clone my fork of the repo: 
`git clone git@github.com:frazar/qcontainers.git`
2. Move to the directory where the repo was cloned: 
`cd qcontainers`
3. Setup cmake: 
`cmake .`
4. Move to the "tests" folder: 
`cd tests`
5. Run the test suite (it will also trigger a qcontainers build): 
`make test`

Unfortunately I don't possess the knowledge required to fix this issue, but I hope that reporting it will help.

**Comment by darmar-lt** [comment]
I will look into the problem. If this problem is not Fortran specific, I will post the message to the qlibc developers.

**Comment by darmar-lt** [comment]
It seems that the last commit solves the reported problem. The tests on qtreetbl_m now reports no break of invariant.

**Comment by frazar** [comment]
I can confirm that the tests are all passing now
