### ISSUE TITLE
I cannot compile it in win7 with vs2013

### ISSUE THREAD

**Issue by ztdepztdep** [darmar-lt/qcontainers#3]
I generate the project with cmake in win7 64bit system.
But it gives me the following error:

Error	35	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	276	1	qcontainers
Error	36	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	293	1	qcontainers
Error	39	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	350	1	qcontainers
Error	40	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	361	1	qcontainers
Error	41	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	387	1	qcontainers
Error	42	error C2065: 'c1' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	406	1	qcontainers
Error	27	error C2065: 'size' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	111	1	qcontainers
Error	28	error C2065: 'size' : undeclared identifier	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	114	1	qcontainers
Error	33	error C2143: syntax error : missing ';' before 'const'	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	262	1	qcontainers
Error	37	error C2143: syntax error : missing ';' before 'const'	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	334	1	qcontainers
Error	26	error C2146: syntax error : missing ';' before identifier 'size'	H:\qcontainers-master\qcontainers-master\utilities\qhash.c	111	1	qcontainers

**Comment by darmar-lt** [comment]
It is strange. I tried qcontainers successfully with VS2015. Perhaps could you shear the cmake generated project file. I will try to look into this problem.

**Comment by darmar-lt** [comment]
Does somebody else is experiencing the same problem? I can't reproduce the compilation errors using VS2015. Without more info, the reported problem can not be solved.

**Comment by ztdepztdep** [comment]
[build.zip](https://github.com/darmar-lt/qcontainers/files/1464676/build.zip)
Sorry for the dealy.
I use vs2013.

**Comment by darmar-lt** [comment]
I have installed VS2013 and compiled containers without any problem. I can't reproduce the reported compilation errors. 

Maybe there is a problem with the installation of VS on your PC? Can you compile some other C/C++ code in VS?

Another thought: why do you want to compile with VS? My guess is that, you want to use qcontainers from Intel Fortran. In that case, you should be aware, that only Intel Fortran 2016 and newer versions implements TS-29113 required by qcontainers library.

**Comment by ztdepztdep** [comment]
Thank you very much! I just installed the vs2015 and intel fortran 2017. and I sucessfully compiled the "qcontainers.lib".
     I tried to compile the "qhashhtbl.f90" with the "qcontainers.lib", I got the following errors:

错误	61	 error #6404: This name does not have a type, and must have an explicit type.   [QTREETBL_GETNAMESIZE_C]	H:\Console2\qtreetbl.F90	754	
错误	123	 error #6404: This name does not have a type, and must have an explicit type.   [QTREETBL_GETNAMESIZE_C]	H:\Console2\lid.f90	754	
错误	60	 error #6404: This name does not have a type, and must have an explicit type.   [QTREETBL_GETOBJ_C]	H:\Console2\qtreetbl.F90	701	
错误	122	 error #6404: This name does not have a type, and must have an explicit type.   [QTREETBL_GETOBJ_C]	H:\Console2\lid.f90	701	

  Could you please give me some suggestions.
Regards

**Comment by darmar-lt** [comment]
Acctully I do not know what is wrong in your case. However, I prepared a small VS2015 project which you can use as a start point. It is Win32 project and it uses qcontainers.lib compiled for Win32. To use it, you should open "test_qcont_1.sln" in VS. Open Properties dialog (Project->Properties). Select Linker->General. Change value in "Additional Library Directories" to the directory where you have your compiled qcontainers.lib file. Make sure that qcontainers.lib is compiled for Win32.
[test_qcont_1.zip](https://github.com/darmar-lt/qcontainers/files/1478832/test_qcont_1.zip)

**Comment by ztdepztdep** [comment]
thank you very much for your kindly help.
I decide to use it in linux system. It seems windows system is very tedious for programming.
